### PR TITLE
testing: Explicitly set round timings

### PR DESCRIPTION
**Pull request by stevenroose**
For just the simple tests we have, this changed the integration test duration from 236 secs to 155 secs on my laptop.

### CODE REVIEW

**Comment by ErikDeSmedt** [comment]
Are we even running the same tests? I have the following timings

- master: 23s
- round-timgs: 26s

PS: I would be interested to have a glimpse on your test-logs to get an idea where time is lost.

**Comment by stevenroose** [comment]
I'm counting the entire invocation, without compilation. `time just test-integration`. My laptop has been laggy lately, but I can't imagine it's a 10x slower than yours :sweat_smile:

**Comment by stevenroose** [comment]
This might give a glimps
```

[16:33:26.201  INFO] Starting aspd-1
[16:33:26.201 TRACE] Preparing aspd-1
test check_aspd_version has been running for over 60 seconds
test fund_asp has been running for over 60 seconds
test check_aspd_version ... ok
[16:34:57.122 TRACE] aspd-1: Trying to spawn "cargo" "run" "--package" "bark-aspd" "--" "--datadir" "/home/steven/code/rust/bark/test/aspd/fund_aspd/aspd-1" "start"
[16:34:59.690  INFO] Started aspd-1
```

The fact that 2 tests are trying to setup an aspd at the same time might not be ideal.

**Comment by stevenroose** [comment]
Running again, I get 337s and 195s. Seems to be wildly unreliable, but I might get some benefit from understanding why that setting up aspd is taking so long. It seems to be the bulk of it.

**Comment by stevenroose** [comment]
Even not doing multiple tests:
`time just test-integration onboard_bark` takes 11s
`time just test-integration multiple_round_payments` takes 88s.

It's hard to use trace logging to find out what's happening under the hood because the logs emissions themselves are subject to the tokio runtime scheduler, I think.

Generally, we might benefit from running integration tests with `--jobs 1` to avoid any races between the tests and to make logs more readable. For me it's not hurting runtime, it's actually slightly better on the times I tried.

**Comment by stevenroose** [comment]
Added a few more things. Could you check if this is hindering you at all?

**Comment by ErikDeSmedt** [comment]
I

> The fact that 2 tests are trying to setup an aspd at the same time might not be ideal.

I think I understand what the problem with slow tests might be.
By default, we run `cargo run --package aspd --` instead of `aspd`.
It appears that on every command you compile `aspd` over and over again.
On my machine the result is cached and the second invocation is immediate.

Could you try to do 

```
cargo build
export ASPD_EXEC=$PWD/target/debug/aspd
export BARK_EXEC=$PWD/target/debug/bark
time just test-integration
```

This should ensure we don't do the compilation-step.

**Comment by stevenroose** [comment]
I don't think I'm compiling it because I see the compilation logs only at the beginning. But let me try that.

**Comment by stevenroose** [comment]
Oh that's a lot faster.

```
just test-integration  28.11s user 6.76s system 112% cpu 31.130 total
```
on master and 


```
just test-integration  27.55s user 5.96s system 127% cpu 26.245 total
```

on this branch.

Yeah then the diff is negligible. 

Then we might not need the last commit. I think explicitly setting round times is probably a good idea anyway.

I get this if I remove the last commit and parallelize again:
```
cargo test --package ark-testing  23.01s user 4.90s system 132% cpu 21.082 total
```

**Comment by stevenroose** [comment]
I removed the last commit from the branch

**Review by ErikDeSmedt — APPROVED** [review]

**Pull request merged**
